---
- hosts: localhost
  connection: local
  become: yes
  vars:
    dependencies:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

  tasks:
    - name: (1/5) Install required dependencies
      apt:
        name: "{{ dependencies }}"
        state: present

    - name: (2/5) Add Docker's official GPG key
      apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present

    - name: (3/5) Add Docker's official APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: (4/5) Install Docker CE
      apt:
        name:
          - docker-ce
        state: present
      notify: 
        - Start Docker

    - name: (5/5) Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64"
        dest: "/usr/local/bin/docker-compose"
        mode: '0755'

    - name: (6/6) Add user to docker group
      user:
        name: "{{ lookup('env', 'USER') }}"
        groups: docker
        append: yes

  handlers:
    - name: Start Docker
      service:
        name: docker
        state: started
