---
- hosts: localhost
  connection: local
  become: yes
  vars:
    dependencies:
      - curl
      - ca-certificates
      - gnupg
      - lsb-release
      - build-essential

  tasks:
    - name: (1/4) Install required dependencies
      apt:
        name: "{{ dependencies }}"
        state: present

    - name: (2/4) Install Redis server from default repositories
      apt:
        name: redis-server
        state: present

    - name: (3/4) Verify Redis installation
      command: redis-server --version
      register: redis_version
      changed_when: false

    - debug:
        msg: "Redis version: {{ redis_version.stdout }}"
